### ISSUE TITLE
pypdfocr.exe is broken because of multiprocessing

### ISSUE THREAD

**Issue by virantha** [virantha/pypdfocr#24]
The PyInstaller package that creates the .exe does not support the multiprocessing library out of the box.  There is a work-around that I will introduce into 0.8.3, but there is no ETA for this release yet.  
http://stackoverflow.com/questions/24944558/pyinstaller-built-windows-exe-fails-with-multiprocessing

Still works fine on windows if you're just running the python script instead of the .exe.

**Comment by matt12eagles** [comment]
This can be fixed by patching the underlying Python 2 bug. Give the error a Google and you can see for yourself. If needed. PM me and I can give you the changes needed in the forking.py file

**Comment by virantha** [comment]
I see the fix for overriding Process, but I don't see a fix for multiprocessing.Pool. (the fix for forking seems to apply only to Python3) This issue also seems marked as dontfix on Pyinstaller2.  If you can send me the changes, please do so. Thanks!  For now, I am just planning to remove multiprocessing from the windows runs (ugly hack).

**Comment by virantha** [comment]
Ok nm, I was able to adapt the solution at https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing and fix this.

**Comment by matt12eagles** [comment]
Excellent thank you Virantha! I apologize for not seeing this until now. Would you mind re-creating a new EXE with the change???? I am having trouble compiling to exe on the machine I am working on (its a terminal server, no py2exe support etc. Currently I can call pypdfocr from winPY but it would be nice to be able to natively grab the return value from the pypdfocr.exe.

**Comment by virantha** [comment]
Oh oops, I did create the exe; just forgot to push to master.  Should be
there now.

**Comment by matt12eagles** [comment]
Thank you Virantha!!!

I really appreciate the work. I'm going to look at speeding up the mergePDF step. It seems the process is quite speedy until merging the PDF at the end. 600 or so page 300DPI PDF's usually take about 6 hours to complete. I'll let you know if I discover anything!

**Comment by virantha** [comment]
Thanks, let me know what you find.  I'm not surprised the merge is slow,
because if I look at the code, it has to write out the pdf after adding
every ocr text page to the original.  If I recall, I had to do it this way,
otherwise PyPDF2 would not let me close the page contain the text to merge
until the very end, causing some systems to run out of file descriptors for
large documents.
