### ISSUE TITLE
I/O Error: Couldn't open file '-list'

### ISSUE THREAD

**Issue by OUsteventhomas** [virantha/pypdfocr#25]
I'm getting this error right before a warning that the program can't execute pdfimages to calculate DPI. I don't think '-file' is a proper flag to pass in to pdfimages.exe. I can generate the same error by running (from the same folder) pdfimages.exe -file "filename.pdf"

Is there maybe a specific pdfimages.exe that is required?

**Comment by virantha** [comment]
Please use pdfimages.exe from Poppler.  Prebuilt binaries for windows here 
http://blog.alivate.com.au/poppler-windows/
