### ISSUE TITLE
File name with escapable HTML character

### ISSUE THREAD

**Issue by trybik** [virantha/pypdfocr#26]
The temporary `PDFNAME_N_preprocess.html` file refers to the corresponding `PDFNAME_N_preprocess.jpg` file (via path: `html/body/div[@id="page_N"]/@title`). If the `PDFNAME` contains escapable HTML character, such as `&`, this character is not escaped in the HTML file, which results in the following parsing error:

    xml.etree.ElementTree.ParseError: not well-formed (invalid token):  line ...

To reproduce rename PDF to `&.pdf` and run:

    pypdfocr \&.pdf

cf:

    tidy -e \&_1_preprocess.html

Best,
Mik

**Comment by virantha** [comment]
This appears to be fixed in 0.9.0.  Closing for now...
