### ISSUE TITLE
Wrong y position 

### ISSUE THREAD

**Issue by Wikunia** [virantha/pypdfocr#27]
Hi, 

first of all thanks for this awesome program. Unfortunately I have a problem:
When I search a string inside the `_ocr` pdf I found the matches but the highlighted part is always around 5 cm (I know that's not the best unit :D ) under the real match.
![pypdfocr](https://cloud.githubusercontent.com/assets/4931746/6173083/89040d28-b2e5-11e4-8369-32d76272b46e.png)

**Comment by virantha** [comment]
Hi Ole, thanks for the feedback. I've noticed this every now and then, but
nothing consistent.
Do you have a pdf you could share that manifests this error so I can take a
stab at tracing it down?

**Comment by Wikunia** [comment]
Hi I can't share the pdf with you but I will looking for another one :) Stay tuned!

**Comment by Wikunia** [comment]
Well it looks fine on any other pdf I tried so don't worry. The important thing is that I can now search inside the pdf! Thanks!!!

**Comment by virantha** [comment]
By any chance, was the "bad" one in landscape and the rest portrait
orienation?

**Comment by Wikunia** [comment]
The "bad" one is a pdf generated generated with latex I think and it looks like an 1:1 ratio.
