### ISSUE TITLE
Make watchdog and evernote optional dependencies

### ISSUE THREAD

**Issue by chmduquesne** [virantha/pypdfocr#29]
Hi,

I don't use evernote and I prefer to use pypdfocr on a non automated basis. Is it possible to import the features optionally (catching the ImportErrors) and remove the dependencies in pypi?

Cheers

**Comment by virantha** [comment]
Sorry, I don't want to overcomplicate the dependencies. Since watchdog and evernote are fairly standard packages, I don't see the value of conditionally importing them...
