### ISSUE TITLE
using pypdfocr from within a python program

### ISSUE THREAD

**Issue by michaelsorich** [virantha/pypdfocr#30]
Hi,

Thanks for making pypdfocr - it fills an important gap. I am interesting in calling for the conversion of a scanned pdf document to a searchable pdf document from within a python program. Is there best practice for doing this? I tried
from pypdfocr.pypdfocr import PyPDFOCR
converter = PyPDFOCR()
converter.go(['pdffilename.pdf'])

The process started but did not run in the same manner as what I get from using pypdfocr from the commmand line. It did not seem to get past the generation of the jpg files. The main issues seemed to be with the multiprocessing module and the need to call freeze_support with windows (using python 2.7 32bit on a windows 7 64 bit machine). Unfortunately my understanding of the multiprocessing module is very limited.
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

I guess that I can get around this by using popen to call pypdfocr from the command line but it seems a little strange given that pypdfocr is written in python. I am happy to do this but if there is a better way please let  me know.

Thanks,

Michael

**Comment by mw44118** [comment]
I also want to use pypdfocr from within python.

**Comment by virantha** [comment]
Unclear why this doesn't work on windows.  Sorry, no time to debug this as it works fine on mac and linux, and there's too many outstanding issues with the multiprocessing module on windows.

**Comment by virantha** [comment]
Actually, see the following:
http://stackoverflow.com/questions/3405397/python-multiprocessing-continuously-spawns-pythonw-exe-processes-without-doing-a

So your example above should be:

    from pypdfocr.pypdfocr import PyPDFOCR
    
    if __name__ == '__main__':
        converter = PyPDFOCR()
        converter.go(['pdffilename.pdf'])
