### ISSUE TITLE
Allow killing the process via Ctrl+C

### ISSUE THREAD

**Issue by zaroth** [virantha/pypdfocr#31]
A custom signal handler for SIGINT to shutdown pypdfocr would be nice, since interrupting the script during 700-page tesseract OCR seems impossible...

**Comment by zaroth** [comment]
Just for reference, stackoverflow threads I found related to the issue:

http://stackoverflow.com/questions/11312525/catch-ctrlc-and-exit-multiprocesses-gracefully-in-python
http://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool

**Comment by virantha** [comment]
Fixed, at least on mac os x; will be released on 0.8.3 shortly
