### ISSUE TITLE
Can't get started

### ISSUE THREAD

**Issue by hjanjua** [virantha/pypdfocr#32]
Hello 

I have installed all the requirements I am getting following error - please help

C:\Users\xxx\Downloads\pypdfocr-0.8.2.tar\dist\pypdfocr-0.8.2\pypdfocr-0.8.2
\pypdfocr>pypdfocr.py filename.pdf
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\pypdfocr-0.8.2.tar\dist\pypdfocr-0.8.2\pypdfo
cr-0.8.2\pypdfocr\pypdfocr.py", line 34, in <module>
    from pypdfocr_filer_evernote import PyFilerEvernote
  File "C:\Users\xxx\Downloads\pypdfocr-0.8.2.tar\dist\pypdfocr-0.8.2\pypdfo
cr-0.8.2\pypdfocr\pypdfocr_filer_evernote.py", line 26, in <module>
    from evernote.api.client import EvernoteClient
ImportError: No module named evernote.api.client

**Comment by virantha** [comment]
It looks like you don't have the python evernote package.  If you're not using pip to install pypdfocr, then please pip install all the dependencies in requirements.txt
