### ISSUE TITLE
Using numeric keywords in config file triggers error

### ISSUE THREAD

**Issue by marklagace** [virantha/pypdfocr#34]
Using an entirely numeric keyword in the config file for automatic filing resulted in the following error for me:
>Traceback (most recent call last):
>  File "/usr/bin/pypdfocr", line 9, in <module>
>    load_entry_point('pypdfocr==0.8.2', 'console_scripts', 'pypdfocr')()
>  File "/usr/lib64/python2.7/site-packages/pypdfocr/pypdfocr.py", line 456, in main
>    script.go(sys.argv[1:])
>  File "/usr/lib64/python2.7/site-packages/pypdfocr/pypdfocr.py", line 423, in go
>    self._setup_filing()
>  File "/usr/lib64/python2.7/site-packages/pypdfocr/pypdfocr.py", line 287, in _setup_filing
>    keywords = [x.lower() for x in keywords]
>AttributeError: 'int' object has no attribute 'lower'

The issue seems to be in the code to make sure the keywords are lower-cased. Typecasting the keyword as a string prior to lower-casing it seems to resolve the issue. I.e.
replace line 287:
```python
keywords = [x.lower() for x in keywords]
```
with:
```python
keywords = [str(x).lower() for x in keywords]
```
I haven't done extensive testing, but with the above modification the programs runs error-free and will successfully match a document based solely on an entirely numeric keyword.

**Comment by virantha** [comment]
fixed, to be released in 0.8.3.  Thanks!
