### ISSUE TITLE
Looking for text.pdf that does not exist

### ISSUE THREAD

**Issue by tadamhicks** [virantha/pypdfocr#41]
When I set up a watch in a directory, I frequently see 

`ERROR: Cannot find specified pdf file /path/to/file_text.pdf`

This does not happen with every pdf I place in there, but when it does the watchdog tips over.

I don't know what it's looking for, and I would like for the watchdog to stay running despite errors.

**Comment by palica** [comment]
You can patch pypdfocr_watcher.py like this:

diff --git a/pypdfocr/pypdfocr_watcher.py b/pypdfocr/pypdfocr_watcher.py
index 73581e0..cb78002 100755
--- a/pypdfocr/pypdfocr_watcher.py
+++ b/pypdfocr/pypdfocr_watcher.py
@@ -93,7 +93,7 @@ class PyPdfWatcher(FileSystemEventHandler):
 
         """
         if ev_path.endswith(".pdf"):
-            if not ev_path.endswith("_ocr.pdf"):
+            if not ev_path.endswith(("_ocr.pdf","_text.pdf")):^M
                 PyPdfWatcher.events_lock.acquire()
                 if not ev_path in PyPdfWatcher.events:
                     PyPdfWatcher.events[ev_path] = time.time()

**Comment by virantha** [comment]
Thanks, I'll try to get this into the next release.

**Comment by mmatiaschek** [comment]
I get this error regularly - a release of 0.9.1 would be great!

**Comment by mmatiaschek** [comment]
Patch works fine, i incorporated it into my docker image...
https://hub.docker.com/r/mmatiaschek/pypdfocr/

**Comment by danmash** [comment]
@mmatiaschek thank you!

**Comment by danmash** [comment]
@virantha You made a typo in  pypdfocr_watcher.py 
`if not ev_path.endswith(("_ocr.pdf", "_test.pdf")):`

`_test` instead of `_text`

**Comment by mattobrien415** [comment]
I am still having this problem using 0.9.1! My monitoring dies. I checked `pypdfocr_watcher.py`, the fix is clearly there.  Am I the only one?  

Only thing I can think of, is that I'm running the process over multiple directories at once.

**Comment by solartune** [comment]
I have the same problem. @virantha please, check the line 
`if not ev_path.endswith(("_ocr.pdf", "_test.pdf")):`
There should be `_text` as said @danmash
