### ISSUE TITLE
Unable to run pypdfocr.exe ver 0.9.0

### ISSUE THREAD

**Issue by violetsolutions** [virantha/pypdfocr#45]
Hi,

I am unable to run pypdfocr.exe 0.9.0 on Windows 7 x64. This is the error message that I get:

`This version of pypdfocr.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.`

**Comment by virantha** [comment]
I have tested on windows 7 x64 and it runs fine for me.  Are you sure you're on 64-bit?  Have you tried an older version of pypdfocr (like 0.8.3) and does that also not work?

**Comment by virantha** [comment]
Closed, unable to reproduce
