### ISSUE TITLE
hocr2pdf.py dropping one character (or last character from) words?

### ISSUE THREAD

**Issue by zhoujianfu** [virantha/pypdfocr#46]
Hi, when I try running hocr2pdf.py on the files I've attached, it mostly works but single character "ocr_words" seem to get lost. Also, sometimes the last character in multi-character words?

Oh wait, this is weird.. when opening them in acrobat reader (on osx) the words are (all but two) there, but when opening them in chrome's PDF viewer, a lot (all?) of the single-character ones are missing! Like, you can't even CTRL-F to find them in the doc in chrome, but (mostly) can in adobe!

I've attached the original jp.jpg, the jp.hocr file, a non-searchable pdf of the jpg (just created by running 'convert jp.jpg jp.pdf') and the result of hocr2pdf.py as jp_ocr.pdf.

Strangely the 発展 characters don't seem to make it to the pdf, even when viewing in adobe (everything else does in adobe).

This is some weird, weird stuff... 
[jp_ocr.pdf](https://github.com/virantha/pypdfocr/files/269412/jp_ocr.pdf)
[jp.pdf](https://github.com/virantha/pypdfocr/files/269413/jp.pdf)
![jp](https://cloud.githubusercontent.com/assets/940578/15343662/8c0e0608-1c53-11e6-8de1-f491717a7940.jpg)

[jp.hocr.txt](https://github.com/virantha/pypdfocr/files/269414/jp.hocr.txt)

Help?

**Comment by zhoujianfu** [comment]
I'm not sure if that hocr file uploaded correctly.. just in case, here it is again?
[jp.hocr.txt](https://github.com/virantha/pypdfocr/files/269415/jp.hocr.txt)

**Comment by virantha** [comment]
Sorry, I don't think I'll be able to help on this.  It seems related to the
particular PDF viewer and the Tesseract OCR engine for your language.  I
have not seen this on english documents.
