### ISSUE TITLE
blPara attribute missing

### ISSUE THREAD

**Issue by MikeLeo40** [virantha/pypdfocr#82]
F29
Python 2.7.15

run this script against PDF and get:
AttributeError: RotatedPara instance has no attribute 'blPara'

Script runs successfully and generates a .hocr file for each page from the pdf...it is in what ever it wants to do next that the blPara attribute does not exist.

Thanks for any pointers.

**Comment by MikeLeo40** [comment]
This is addressed here https://github.com/virantha/pypdfocr/issues/80

downgrade to reportlab 3.4.0 fixes the issue for me.

**Comment by BobStein** [comment]
In case anyone else gets this same error message, I got it on p.drawOn() after calling **p.wrap() with availWidth=0**. Reportlab version 3.4.0 absorbed this silently, but 3.6.12 raised this obtuse exception.

```
File "/usr/local/lib/python3.10/dist-packages/reportlab/platypus/paragraph.py", line 2464, in drawPara
  blPara = self.blPara
AttributeError: 'Paragraph' object has no attribute 'blPara'
```
