### ISSUE TITLE
pypdfocr error [ValueError: invalid literal for int() with base 10: ''] in '\pypdfocr_pdf", line 98, in overlay_hocr'

### ISSUE THREAD

**Issue by hsh001** [virantha/pypdfocr#9]
win7 x64 / pypdfocr-0.6 / ghostscript-9.10 / tesseract-3.02

Fail on all pdf files...

Read in configuration file
{'ghostscript': {'binary': 'D:/res-bin/ghostscript-9.10/bin/gswin64c.exe'}, 'tesseract': {'binary': 'D:/res-bin/__tesseract-ocr/tesseract.exe'}}
Setting location for tesseract executable to "D:/res-bin/__tesseract-ocr/tesseract.exe"
Setting location for ghostscript executable to "D:/res-bin/ghostscript-9.10/bin/gswin64c.exe"
Starting conversion of D:\res-dev\2014\ocrpdf_inp\1.pdf
Running ghostscript on D:\res-dev\2014\ocrpdf_inp\1.pdf to create D:\res-dev\2014\ocrpdf_inp\1.tiff
"D:/res-bin/ghostscript-9.10/bin/gswin64c.exe" -q -dNOPAUSE -sDEVICE=tiff24nc -r300 -sOutputFile="D:\res-dev\2014\ocrpdf_inp\1.tiff" "D:\res-dev\2014\ocrpdf_inp\1.pdf" -c quit
Created D:\res-dev\2014\ocrpdf_inp\1.tiff
"D:/res-bin/ghostscript-9.10/bin/gswin64c.exe" -q -dNOPAUSE -sDEVICE=jpeg -dJPEGQ=75 -r200 -sOutputFile="D:\res-dev\2014\ocrpdf_inp\1%d.jpg" "D:\res-dev\2014\ocrpdf_inp\1.pdf" -c quit
Checking tesseract version
"D:/res-bin/__tesseract-ocr/tesseract.exe" -v
Running OCR on D:\res-dev\2014\ocrpdf_inp\1.tiff to create D:\res-dev\2014\ocrpdf_inp\1.html
"D:/res-bin/__tesseract-ocr/tesseract.exe" "D:\res-dev\2014\ocrpdf_inp\1.tiff" "D:\res-dev\2014\ocrpdf_inp\1" hocr
Tesseract Open Source OCR Engine v3.02 with Leptonica
Page 1 of 2
Page 2 of 2
Created D:\res-dev\2014\ocrpdf_inp\1.html
hocr_filename:D:\res-dev\2014\ocrpdf_inp\1.html, hocr_dir:D:\res-dev\2014\ocrpdf_inp, hocr_basename:1.html
Overlaying hocr and creating final 1_ocr.pdf
Analyzing OCR and applying text to PDF...
Searching for 1*.jpg
Adding page image 11.jpg
Page width=842.040000, height=595.080000
Traceback (most recent call last):
  File "<string>", line 408, in <module>
  File "<string>", line 405, in main
  File "<string>", line 395, in go
  File "<string>", line 306, in run_conversion
  File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows\out00-PYZ.pyz\pypdfocr_pdf", line 98, in overlay_hocr
<b>
ValueError: invalid literal for int() with base 10: ''
</b>

<b>
file 'pypdfocr_pdf.py'
[
line 98 : 'pg_num = int(jpg_file.split(basename)[1].split('.')[0])'
]
</b>

file 'config.yaml'
[
tesseract:
    binary: D:/res-bin/__tesseract-ocr/tesseract.exe
ghostscript:
    binary: D:/res-bin/ghostscript-9.10/bin/gswin64c.exe
]
![bug](https://f.cloud.github.com/assets/6611621/2106343/e4ae852a-8fa2-11e3-8458-4fd1f4a387b5.png)

**Comment by farrukhdGB** [comment]
I see the same issue in the latest version. Any idea?

![image](https://user-images.githubusercontent.com/30141495/28247244-16f530ac-6a2d-11e7-82ab-36c4941af62e.png)

**Comment by kaumaron** [comment]
@farrukhdGB , I know you asked about a year ago but for posterity:
I had to downgrade from tesseract-4.00.00 to tesseract-3.05.02 to get it to work.
According to one of the posts on [Bounty Source](https://www.bountysource.com/issues/42952193-error-on-running-pypdfocr) it's throwing that error on the tesseract version name.

Edit: it's a reference to [Issue #61](https://github.com/virantha/pypdfocr/issues/61).

**Comment by tbirdss** [comment]
> I had to downgrade from tesseract-4.00.00 to tesseract-3.05.02 to get it to work.
---
https://digi.bib.uni-mannheim.de/tesseract/
